-- 20221113
-- 修改故障的故障描述、原因措施描述长度限制
ALTER TABLE BU_FAULT_INFO MODIFY FAULT_DESC VARCHAR2(1000);
ALTER TABLE BU_FAULT_HANDLE_RECORD MODIFY REASON_DESC VARCHAR2(1000);
ALTER TABLE BU_FAULT_HANDLE_RECORD MODIFY SOLUTION_DESC VARCHAR2(1000);
-- 必换件清单加字段：有效无效
ALTER TABLE BU_MATERIAL_MUST_LIST ADD (status SMALLINT DEFAULT 1 NOT NULL);
COMMENT on COLUMN BU_MATERIAL_MUST_LIST.status is '状态 0无效1有效';
-- 作业记录检查结果加字段：同检人员id、同检人员名称
ALTER TABLE BU_PL_WORK_RECORD_RESULT ADD (together_check_user_ids VARCHAR2(500) NULL);
COMMENT on COLUMN BU_PL_WORK_RECORD_RESULT.together_check_user_ids is '同检人员ids';
ALTER TABLE BU_PL_WORK_RECORD_RESULT ADD (together_check_user_names VARCHAR2(500) NULL);
COMMENT on COLUMN BU_PL_WORK_RECORD_RESULT.together_check_user_names is '同检人员名称s';

-- 20221114
-- 修改故障的故障描述、原因措施描述长度限制
-- 故障原因描述和处理描述仅支持250字符（maximo及移动巡检系统和施工调度系统限制）
ALTER TABLE BU_FAULT_INFO MODIFY FAULT_DESC VARCHAR2(500);
ALTER TABLE BU_FAULT_HANDLE_RECORD MODIFY REASON_DESC VARCHAR2(500);
ALTER TABLE BU_FAULT_HANDLE_RECORD MODIFY SOLUTION_DESC VARCHAR2(500);
-- 系统日志表建索引
CREATE INDEX indx_sys_log_type ON SYS_LOG(LOG_TYPE) TABLESPACE TIROSDATA;
-- 交接车、列计划加字段：是否历史数据
ALTER TABLE BU_REPAIR_EXCHANG ADD (history_data SMALLINT DEFAULT 0 NOT NULL);
COMMENT on COLUMN BU_REPAIR_EXCHANG.history_data is '是否历史数据 0否1是';
ALTER TABLE BU_REPAIR_PLAN ADD (history_data SMALLINT DEFAULT 0 NOT NULL);
COMMENT on COLUMN BU_REPAIR_PLAN.history_data is '是否历史数据 0否1是';

-- 20221117
-- 修改领料单的物料消耗状态长度限制
ALTER TABLE BU_MATERIAL_APPLY MODIFY SYNC_RESULT VARCHAR2(4000);
